# Generated by Django 4.2.16 on 2024-11-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("Gas Leakage", "Gas Leakage"),
                    ("Meter Issue", "Meter Issue"),
                    ("Billing Issue", "Billing Issue"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Resolved", "Resolved"),
                ],
                db_index=True,
                default="Pending",
                max_length=20,
            ),
        ),
    ]
