# Generated by Django 5.1 on 2024-11-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "report_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("xls", "Excel")], max_length=50
                    ),
                ),
            ],
        ),
    ]
