# Generated by Django 4.2.16 on 2024-11-18 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="is_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="report",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("xls", "Excel")], db_index=True, max_length=50
            ),
        ),
    ]
