# Generated by Django 4.2.16 on 2024-11-18 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="level",
            field=models.CharField(
                choices=[("INFO", "INFO"), ("WARNING", "WARNING"), ("ERROR", "ERROR")],
                default="'info'",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="logentry",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_entries",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
